server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-locations: classpath:db/changelog/db.changelog-master.xml
